### ISSUE TITLE
[Navigation] Dodge Jump

### ISSUE THREAD

**Issue by jesselloyd** [jesselloyd/prime#13]
[DEPENDS ON #8]
As a player, I want the ability to jump in a given direction resulting in a dodge. 

**Use Cases**

Use case: A player is moving in a direction and jumps. The jump will change the player's position based on the following rules and assumptions:
- The direction of movement will determine the horizontal direction of the jump.
- There will be a temporary increase in vertical position for the duration of the jump.
- The jump will move the character 2 times the distance of a regular unit of movement.
- The user will not be able to jump again until enough time has passed to cover 2 times the distance of a regular unit of movement. (This prevents players spamming jumps, and allows another player to jump and catch up to the player in the same timeframe)

**Comment by everythingEzra2** [comment]
Basic & crude jump is implemented, we'll have to polish this later to make the jump work with the gameplay
